// <auto-generated />
namespace AdminPanel.DataAccessLayer.AdminPanelMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LessProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LessProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201602161920049_LessProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
